const data = [
  {
    id: 1,
    img: "./images/img1.jpg",
    price: 35,
    name: "JavaScript Book",
    category: "books",
  },
  { id: 2, img: "./images/img2.jpg", price: 35, name: "History book", category: "books" },
  {
    id: 3,
    img: "./images/img3.jpg",
    price: 50,
    name: "acer laptop",
    category: "computer",
  },
  { id: 4, img: "./images/img4.jpg", price: 35, name: "ballpoint pen", category: "pens" },
  {
    id: 5,
    img: "./images/img1.jpg",
    price: 2,
    name: "JavaScript Book",
    category: "books",
  },
  { id: 6, img: "./images/img2.jpg", price: 35, name: "History book", category: "books" },
  {
    id: 7,
    img: "./images/img3.jpg",
    price: 75,
    name: "acer laptop",
    category: "computer",
  },
  {
    id: 8,
    img: "./images/img1.jpg",
    price: 90,
    name: "JavaScript Book",
    category: "books",
  },
  {
    id: 9,
    img: "./images/img3.jpg",
    price: 84,
    name: "acer laptop",
    category: "computer",
  },
  {
    id: 10,
    img: "./images/img4.jpg",
    price: 73,
    name: "ballpoint pen",
    category: "pens",
  },
  {
    id: 11,
    img: "./images/img1.jpg",
    price: 12,
    name: "JavaScript Book",
    category: "books",
  },
  {
    id: 12,
    img: "./images/img3.jpg",
    price: 21,
    name: "acer laptop",
    category: "computer",
  },
];
export default data;
